# SPDX-FileCopyrightText: Copyright 2024 Mark Rotteveel
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "Firebird External Table Generator"
SPDX-PackageSupplier = "Mark Rotteveel <mark@lawinegevaar.nl>"
SPDX-PackageDownloadLocation = "https://github.com/mrotteveel/ext-table-gen"

[[annotations]]
path = "NOTICE"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2023 Mark Rotteveel"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "gradle/wrapper/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Gradle Inc. and/or \"the original authors\""
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "src/docs/asciidoc/chapters/data/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2023-2024 Mark Rotteveel"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["src/test/resources/testdata/ATTRIBUTION.adoc", "src/test/resources/testdata/happypath-config.xml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2023-2024 Mark Rotteveel"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "src/test/resources/testdata/customers-10.csv"
precedence = "aggregate"
SPDX-FileCopyrightText = "Datablist"
SPDX-License-Identifier = "LicenseRef-Datablist"

[[annotations]]
path = "src/integrationTest/resources/integration-testcases/verify-alignment-testcases.csv"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2023-2024 Mark Rotteveel"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "src/integrationTest/resources/integration-testdata/ATTRIBUTION.adoc"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2023 Mark Rotteveel"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "src/integrationTest/resources/integration-testdata/customers-1000.csv"
precedence = "aggregate"
SPDX-FileCopyrightText = "Datablist"
SPDX-License-Identifier = "LicenseRef-Datablist"

[[annotations]]
path = "src/integrationTest/resources/integration-testdata/**-values-**.csv"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2023-2024 Mark Rotteveel"
SPDX-License-Identifier = "Apache-2.0"
